spring:
  application:
    name: cinema-loyalty

server:
  port: 8084

grpc:
  server:
    port: 9091

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
