spring:
  application:
    name: cinema-analytics-server

server:
  port: 8085

grpc:
  server:
    port: 9092

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
